name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-19.09
      - uses: cachix/cachix-action@v6
        with:
          name: arximboldi
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-build

  dev:
    strategy:
      matrix:
        type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v6
        with:
          name: arximboldi
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-shell --run "mkdir build"
      - name: configure cmake
        run: |
          nix-shell --run "
            cd build && cmake .. \
              -DCMAKE_BUILD_TYPE=${{ matrix.type }}
          "
      - run: nix-shell --run "cd build && make all -j`nproc`"
